### PR TITLE
support ruby3 kwargs syntax

### PR DESCRIPTION
**Pull request by konpyu**
This PR supports Ruby 3.0 kwargs syntax to work with both ruby2 and ruby3 🙇 .

### CODE REVIEW

**Comment by r7kamura** [comment]
Thanks!

**Comment by r7kamura** [comment]
~~But I think it should take a Hash instead of keyword arguments, so I'll change it a bit.~~ canceled.

**Comment by r7kamura** [comment]
Released v0.3.0. Thanks for your contribution! 🎉 

- https://rubygems.org/gems/json_world/versions/0.3.0
- https://github.com/r7kamura/json_world/releases/tag/v0.3.0

**Comment by konpyu** [comment]
Thank you! 🎉

**Pull request merged**
