### PR TITLE
Enable define targetSchema field

### PR DESCRIPTION
**Pull request by yuemori**
This gem is very useful and powerful solution for JSON Schema.
I am always grateful for your solutions.

And this time, I would like to enable define to "targetSchema" field.
I hope you are able to merge, if you think to goodness!

Thanks.

### CODE REVIEW

**Comment by r7kamura** [comment]
Thanks @yuemori, it looks nice!

I think that `:target_schema` might be better than `:responses`. What do you think?

**Comment by yuemori** [comment]
Thanks to reply!

I think this gem have the HTTP like view of the world by `parameter` field.
But, I noticed that and misundarstanding from your reply.

I rename and repush this PR.

**Comment by r7kamura** [comment]
Just merged and released v0.2.3 :gem: :sparkles:

**Comment by yuemori** [comment]
I'm happy, thanks :gem: :tada:

**Pull request merged**
